print("Welcome to Band Name Generator")
print("What's the name of the city you grew up in?")
city = input("")
print("What's your Pet's name?")
pet = input("")
print("Your Band name could be "+city+" "+pet)